
public class lastPage extends javax.swing.JFrame {

    int add = 0;
    int front, back;
    int size;
    int[] item;

    public lastPage() {

        front = -1;
        back = -1;
        size = 5;
        item = new int[size];

        initComponents();
    }

    boolean isFull() {
        return back == size - 1;
    }

    boolean isEmpty() {
        return front == -1;
    }

    public void goInLine(int x) {

        if (isFull()) {
            tsik.setText("Full");
            add = 5;
        } else {
            front = 0;
            back++;
            item[back] = x;
            if (add == 1) {
                una.setText(String.valueOf(x));
            } else if (add == 2) {
                pangalawa.setText(String.valueOf(x));
            } else if (add == 3) {
                pangatlo.setText(String.valueOf(x));
            } else if (add == 4) {
                pangapat.setText(String.valueOf(x));
            } else {
                panglima.setText(String.valueOf(x));
            }
        }
    }

    public int checkOut() {
        int x;
        if (isEmpty()) {
            tsik.setText("Empty");
            return -1;
        } else {
            x = item[0];

            for (int i = 0; i < back; i++) {
                item[i] = item[i + 1];
            }

            item[back] = 0;
            back--;
            add--;

            if (add == 4) {
                una.setText(pangalawa.getText());
                pangalawa.setText(pangatlo.getText());
                pangatlo.setText(pangapat.getText());
                pangapat.setText(panglima.getText());
                panglima.setText("");
            } else if (add == 3) {
                una.setText(pangalawa.getText());
                pangalawa.setText(pangatlo.getText());
                pangatlo.setText(pangapat.getText());
                pangapat.setText("");
            } else if (add == 2) {
                una.setText(pangalawa.getText());
                pangalawa.setText(pangatlo.getText());
                pangatlo.setText("");
            } else if (add == 1) {
                una.setText(pangalawa.getText());
                pangalawa.setText("");
            } else if (add == 0) {
                una.setText("");
            }

            if (back < 0) {
                front = -1;
                back = -1;
            }

            return x;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panglima = new javax.swing.JLabel();
        pangapat = new javax.swing.JLabel();
        pangatlo = new javax.swing.JLabel();
        pangalawa = new javax.swing.JLabel();
        una = new javax.swing.JLabel();
        tsik = new javax.swing.JLabel();
        checkOut = new javax.swing.JLabel();
        fil = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        lil = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        exitBtn = new javax.swing.JLabel();
        goInLine = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panglima.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panglima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(panglima, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 80, 70));

        pangapat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pangapat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(pangapat, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 80, 70));

        pangatlo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pangatlo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(pangatlo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 80, 70));

        pangalawa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pangalawa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(pangalawa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 80, 70));

        una.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        una.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(una, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 80, 70));

        tsik.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tsik.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elements", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(tsik, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 440, 60));

        checkOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkOutMouseClicked(evt);
            }
        });
        getContentPane().add(checkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 130, 40));

        fil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filMouseClicked(evt);
            }
        });
        getContentPane().add(fil, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 140, 40));

        show.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        show.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Show Case", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 130, 50));

        lil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lilMouseClicked(evt);
            }
        });
        getContentPane().add(lil, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 130, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2(2).png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));

        exitBtn.setText("jLabel1");
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 90, 70));

        goInLine.setText("jLabel1");
        goInLine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goInLineMouseClicked(evt);
            }
        });
        getContentPane().add(goInLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 130, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitBtnMouseClicked

    private void goInLineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goInLineMouseClicked
        add++;
        int randomNum = (int) (Math.random() * 101);
        if (add > 0) {
            tsik.setText("");
        }
        show.setText("");
        goInLine(randomNum);
    }//GEN-LAST:event_goInLineMouseClicked

    private void checkOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkOutMouseClicked
        if (add == 5) {
            tsik.setText("");
        }
        show.setText("");
        checkOut();
    }//GEN-LAST:event_checkOutMouseClicked

    private void filMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filMouseClicked
        if (front >= 0) {
            show.setText(String.valueOf(item[front]));
        } else {
            tsik.setText("Empty");

        }
    }//GEN-LAST:event_filMouseClicked

    private void lilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lilMouseClicked
        if (back >= 0) {
            show.setText(String.valueOf(item[back]));
        } else {
            tsik.setText("Empty");

        }
    }//GEN-LAST:event_lilMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lastPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lastPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lastPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lastPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lastPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel checkOut;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel fil;
    private javax.swing.JLabel goInLine;
    private javax.swing.JLabel lil;
    private javax.swing.JLabel pangalawa;
    private javax.swing.JLabel pangapat;
    private javax.swing.JLabel pangatlo;
    private javax.swing.JLabel panglima;
    private javax.swing.JLabel show;
    private javax.swing.JLabel tsik;
    private javax.swing.JLabel una;
    // End of variables declaration//GEN-END:variables
}
